import { Platform, StyleSheet } from 'react-native';
import { neonPrimaryButtonExtras } from './neonButtonExtras';
import type { ThemeColors } from './tokens';

/** Estilos do ecrã Atendimento alinhados ao tema (cartões, dashboard). */
export function buildAtendimentoStyles(c: ThemeColors) {
  return StyleSheet.create({
    scroll: { flex: 1, backgroundColor: c.bg },
    container: { padding: 20, paddingBottom: 48 },
    center: { flex: 1, backgroundColor: c.bg, padding: 24, justifyContent: 'center' },
    title: { fontSize: 20, fontWeight: '800', color: c.text, marginBottom: 8 },
    hint: { fontSize: 14, color: c.textSecondary, lineHeight: 21, marginBottom: 16 },
    hintSmall: { fontSize: 12, color: c.textMuted, lineHeight: 18, marginBottom: 10 },
    recebedorWrap: { marginBottom: 8, zIndex: 20 },
    inputRecebedor: { marginBottom: 0 },
    sugestoesBox: {
      marginTop: 6,
      maxHeight: 220,
      backgroundColor: c.surfaceElevated,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: c.sugestaoBorder,
      overflow: 'hidden',
      elevation: 6,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      shadowRadius: 6,
    },
    sugestoesScroll: { maxHeight: 220 },
    sugestaoRow: {
      paddingVertical: 12,
      paddingHorizontal: 14,
      borderBottomWidth: 1,
      borderBottomColor: c.border,
    },
    sugestaoNome: { color: c.text, fontWeight: '700', fontSize: 15 },
    sugestaoMeta: { color: c.textSecondary, fontSize: 12, marginTop: 4 },
    docListaWrap: { marginBottom: 8, zIndex: 10 },
    inputDocLista: { marginBottom: 0 },
    docsMaterialBox: {
      marginTop: 6,
      maxHeight: 280,
      backgroundColor: c.surfaceElevated,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: c.indigoPanel,
      overflow: 'hidden',
      padding: 10,
    },
    docsMaterialScroll: { maxHeight: 260 },
    docsMaterialTit: { color: c.docsMaterialTit, fontSize: 12, fontWeight: '700', marginBottom: 8 },
    docsMaterialEmpty: { color: c.textSecondary, fontSize: 13, lineHeight: 19 },
    docsMaterialRow: {
      paddingVertical: 10,
      paddingHorizontal: 10,
      borderRadius: 8,
      backgroundColor: c.cardNested,
      borderWidth: 1,
      borderColor: c.border,
      marginBottom: 8,
    },
    docsMaterialRowSelected: {
      backgroundColor: c.drawerItemActiveBg,
      borderWidth: 2,
      borderColor: c.accent,
    },
    docsMaterialRowTit: { color: c.text, fontWeight: '700', fontSize: 14 },
    docsMaterialRowTitSelected: { color: c.text, fontWeight: '800' },
    docsMaterialRowSub: { color: c.textSecondary, fontSize: 12, marginTop: 4 },
    docsMaterialRowMeta: { color: c.success, fontSize: 12, marginTop: 6, fontWeight: '600' },
    label: { color: c.formLabel, fontSize: 13, fontWeight: '600', marginBottom: 6, marginTop: 8 },
    input: {
      backgroundColor: c.inputBg,
      borderWidth: 1,
      borderColor: c.border,
      borderRadius: 10,
      padding: 14,
      color: c.text,
      fontSize: 16,
      marginBottom: 8,
    },
    inQ: {
      width: 88,
      backgroundColor: c.inputBg,
      borderWidth: 1,
      borderColor: c.border,
      borderRadius: 8,
      padding: 8,
      color: c.text,
      fontSize: 15,
      textAlign: 'right',
    },
    btn: {
      backgroundColor: c.primaryBtn,
      padding: 16,
      borderRadius: 10,
      alignItems: 'center',
      marginBottom: 10,
      ...neonPrimaryButtonExtras(c),
    },
    btnSec: {
      backgroundColor: c.secondaryBtn,
      padding: 14,
      borderRadius: 10,
      alignItems: 'center',
      marginBottom: 8,
    },
    btnOk: {
      backgroundColor: c.successBtn,
      padding: 16,
      borderRadius: 10,
      alignItems: 'center',
      marginTop: 16,
      ...neonPrimaryButtonExtras(c),
    },
    btnOff: { opacity: 0.5 },
    btnText: { color: c.primaryBtnText, fontWeight: '700', fontSize: 16 },
    btnTextSec: { color: c.id === 'claroSistema' ? c.text : '#e2e8f0', fontWeight: '700', fontSize: 15 },
    meta: { fontSize: 12, color: c.textMuted, marginBottom: 8 },
    meta2: { fontSize: 11, color: c.textSecondary, marginTop: 4 },
    err: { color: c.err, marginBottom: 8, fontSize: 13 },
    warn: { color: c.warn, marginBottom: 8, fontSize: 13 },
    warnDestaque: {
      marginBottom: 12,
      padding: 14,
      borderRadius: 12,
      borderWidth: 2,
      borderColor: c.accent,
      backgroundColor: c.cardNested,
    },
    warnDestaqueTit: { color: c.accent, fontWeight: '800', fontSize: 14, marginBottom: 8 },
    warnDestaqueTxt: { color: c.textSecondary, fontSize: 13, lineHeight: 20 },
    card: {
      marginTop: 12,
      padding: 16,
      backgroundColor: c.card,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: c.border,
    },
    cardTitle: { color: c.text, fontWeight: '800', fontSize: 16 },
    cardSub: { color: c.textSecondary, fontSize: 13, marginTop: 4, marginBottom: 12 },
    subTit: { color: c.formLabel, fontWeight: '700', marginBottom: 10, fontSize: 14, marginTop: 4 },
    rowBarras: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 12, flexWrap: 'wrap' },
    inQtdBarras: { flex: 1, minWidth: 72, marginBottom: 0 },
    btnBarras: { paddingHorizontal: 14, marginBottom: 0 },
    btnBarrasGo: { paddingHorizontal: 16, marginBottom: 0 },
    sessaoBarrasBox: {
      marginBottom: 12,
      padding: 12,
      backgroundColor: c.sessaoBg,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: c.border,
    },
    sessaoBarrasTxt: { color: c.textSecondary, fontSize: 13, lineHeight: 19, marginBottom: 10 },
    btnSessaoFim: {
      backgroundColor: c.secondaryBtn,
      padding: 12,
      borderRadius: 10,
      alignItems: 'center',
    },
    scannerWrap: { flex: 1, backgroundColor: '#000', justifyContent: 'center' },
    scannerDenied: { flex: 1, justifyContent: 'center', padding: 24 },
    scannerDeniedTxt: { color: c.modalText, textAlign: 'center', fontSize: 16 },
    scannerClose: {
      position: 'absolute',
      top: 56,
      right: 16,
      backgroundColor: c.scannerCloseBg,
      paddingVertical: 10,
      paddingHorizontal: 16,
      borderRadius: 10,
    },
    scannerCloseTxt: { color: c.text, fontWeight: '700', fontSize: 16 },
    compModalOverlay: {
      flex: 1,
      backgroundColor: c.modalOverlay,
      justifyContent: 'center',
      alignItems: 'center',
      padding: 20,
    },
    compModalCard: {
      width: '100%',
      maxWidth: 420,
      maxHeight: '88%',
      backgroundColor: c.modalCard,
      borderRadius: 22,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.border,
      padding: 18,
      overflow: 'hidden',
      ...Platform.select({
        ios: {
          shadowColor: '#000',
          shadowOffset: { width: 0, height: 10 },
          shadowOpacity: 0.26,
          shadowRadius: 18,
        },
        android: { elevation: 12 },
        default: {},
      }),
    },
    compModalTit: { color: c.accent, fontWeight: '800', fontSize: 17, marginBottom: 6, textAlign: 'center' },
    compModalSub: { color: c.textMuted, fontSize: 11, marginBottom: 10 },
    compModalScroll: { maxHeight: Platform.OS === 'web' ? 480 : 420, marginBottom: 12 },
    compModalTxt: { color: c.modalText, fontSize: 13, lineHeight: 20 },
    /** Texto do recibo: quebra linhas longas (códigos/descrições) sem cortar na pré-visualização. */
    compModalTxtMono: {
      fontFamily: Platform.select({ ios: 'Menlo', android: 'monospace', default: 'monospace' }),
      fontSize: 11,
      lineHeight: 17,
      letterSpacing: 0.1,
      flexShrink: 1,
      maxWidth: '100%',
    },
    compModalBtnWa: {
      backgroundColor: '#25D366',
      paddingVertical: 14,
      borderRadius: 10,
      alignItems: 'center',
      marginBottom: 8,
    },
    compModalBtnWaTxt: { color: '#fff', fontWeight: '800', fontSize: 16 },
    compModalBtnPrint: {
      backgroundColor: c.compModalBtnPrint,
      paddingVertical: 14,
      borderRadius: 10,
      alignItems: 'center',
      marginBottom: 8,
    },
    compModalBtnPrintTxt: { color: c.text, fontWeight: '700', fontSize: 16 },
    compModalBtnShare: {
      backgroundColor: c.compModalBtnShare,
      paddingVertical: 14,
      borderRadius: 10,
      alignItems: 'center',
      marginBottom: 8,
    },
    compModalBtnShareTxt: { color: c.modalText, fontWeight: '700', fontSize: 15 },
    compModalBtnClose: {
      paddingVertical: 12,
      borderRadius: 10,
      alignItems: 'center',
      marginTop: 4,
    },
    compModalBtnCloseTxt: { color: c.textSecondary, fontWeight: '600', fontSize: 15 },
    row: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: 8,
      paddingVertical: 10,
      borderBottomWidth: 1,
      borderBottomColor: c.rowBorder,
    },
    rowSemSaldo: {
      backgroundColor: c.semSaldoBg,
      borderLeftWidth: 5,
      borderLeftColor: c.semSaldoBorder,
      paddingLeft: 12,
      paddingRight: 10,
      paddingVertical: 12,
      marginVertical: 6,
      borderRadius: 10,
      borderBottomWidth: 0,
      borderWidth: 1,
      borderColor: c.semSaldoBorderSoft,
    },
    rowTxt: { flex: 1 },
    cod: { color: c.accentCode, fontWeight: '700', fontSize: 14 },
    codSemSaldo: { color: c.codSemSaldo },
    desc: { color: c.textSecondary, fontSize: 12, marginTop: 2 },
    descSemSaldo: { color: c.descSemSaldo },
    metaSemSaldo: { color: c.metaSemSaldo, fontWeight: '700', fontSize: 12 },
    badgeSemSaldo: {
      color: c.badgeSemSaldo,
      fontWeight: '800',
      fontSize: 12,
      marginTop: 8,
      lineHeight: 17,
    },
    inQSemSaldo: {
      opacity: 0.45,
      backgroundColor: c.inQSemSaldoBg,
      borderColor: c.inQSemSaldoBorder,
      color: c.inQSemSaldoText,
    },
  });
}
