import { StyleSheet } from 'react-native';
import { neonPrimaryButtonExtras } from './neonButtonExtras';
import type { ThemeColors } from './tokens';

export function buildConsultaStyles(c: ThemeColors) {
  return StyleSheet.create({
    center: { flex: 1, padding: 24, justifyContent: 'center', backgroundColor: c.bg },
    scroll: { flex: 1, backgroundColor: c.bg },
    container: { padding: 20, paddingBottom: 40 },
    title: { fontSize: 22, fontWeight: '800', color: c.text, marginBottom: 10 },
    hint: { fontSize: 14, color: c.textSecondary, lineHeight: 22, marginBottom: 16 },
    hintSmall: { fontSize: 13, color: c.textMuted, lineHeight: 19, marginBottom: 10 },
    btn: {
      backgroundColor: c.primaryBtn,
      padding: 16,
      borderRadius: 10,
      alignItems: 'center',
      marginBottom: 10,
      ...neonPrimaryButtonExtras(c),
    },
    btnOff: { opacity: 0.5 },
    btnText: { color: c.primaryBtnText, fontWeight: '700', fontSize: 16 },
    btnSec: {
      backgroundColor: c.secondaryBtn,
      padding: 14,
      borderRadius: 10,
      alignItems: 'center',
      marginBottom: 10,
    },
    btnTextSec: { color: c.id === 'claroSistema' ? c.text : '#e2e8f0', fontWeight: '700', fontSize: 15 },
    btnOk: {
      backgroundColor: c.id === 'neonVerde' ? c.primaryBtn : c.accent,
      padding: 14,
      borderRadius: 10,
      alignItems: 'center',
      flex: 1,
      ...neonPrimaryButtonExtras(c),
    },
    meta: { fontSize: 12, color: c.textMuted, marginBottom: 8 },
    err: { color: c.err, marginBottom: 8, fontSize: 13 },
    warn: { color: c.warn, marginBottom: 8, fontSize: 13 },
    warnDestaque: {
      marginBottom: 12,
      padding: 14,
      borderRadius: 12,
      borderWidth: 2,
      borderColor: c.accent,
      backgroundColor: c.cardNested,
    },
    warnDestaqueTit: { color: c.accent, fontWeight: '800', fontSize: 14, marginBottom: 8 },
    warnDestaqueTxt: { color: c.textSecondary, fontSize: 13, lineHeight: 20 },
    subTit: { color: c.text, fontWeight: '800', fontSize: 17, marginTop: 16, marginBottom: 6 },
    subTit2: { color: c.formLabel, fontWeight: '700', marginBottom: 10, fontSize: 14, marginTop: 4 },
    input: {
      backgroundColor: c.inputBg,
      borderWidth: 1,
      borderColor: c.border,
      borderRadius: 10,
      padding: 14,
      color: c.text,
      fontSize: 16,
      marginBottom: 8,
    },
    card: {
      marginTop: 12,
      padding: 16,
      backgroundColor: c.card,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: c.border,
    },
    cardTitle: { color: c.text, fontWeight: '800', fontSize: 16 },
    cardSub: { color: c.textSecondary, fontSize: 13, marginTop: 4, marginBottom: 12 },
    row: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      paddingVertical: 10,
      borderBottomWidth: 1,
      borderBottomColor: c.rowBorder,
    },
    rowSemSaldo: {
      backgroundColor: c.semSaldoBg,
      borderLeftWidth: 5,
      borderLeftColor: c.semSaldoBorder,
      paddingLeft: 12,
      paddingRight: 10,
      paddingVertical: 12,
      marginVertical: 6,
      borderRadius: 10,
      borderBottomWidth: 0,
      borderWidth: 1,
      borderColor: c.semSaldoBorderSoft,
    },
    rowConferenciaDiv: {
      borderLeftWidth: 4,
      borderLeftColor: c.err,
      paddingLeft: 10,
      marginVertical: 4,
      paddingVertical: 10,
      backgroundColor: c.cardNested,
      borderRadius: 8,
      borderBottomWidth: 0,
    },
    rowTxt: { flex: 1 },
    cod: { color: c.accentCode, fontWeight: '700', fontSize: 14 },
    codConferenciaDiv: { color: c.err },
    codSemSaldo: { color: c.codSemSaldo },
    desc: { color: c.textSecondary, fontSize: 12, marginTop: 2 },
    descSemSaldo: { color: c.descSemSaldo },
    meta2: { fontSize: 11, color: c.textSecondary, marginTop: 4 },
    metaSemSaldo: { color: c.metaSemSaldo, fontWeight: '700', fontSize: 12 },
    badgeSemSaldo: {
      color: c.badgeSemSaldo,
      fontWeight: '800',
      fontSize: 12,
      marginTop: 8,
      lineHeight: 17,
    },
    rowBarras: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 12, flexWrap: 'wrap' },
    btnBarras: { paddingHorizontal: 16, marginBottom: 0, flex: 0 },
    btnBarrasGo: { flex: 1, marginBottom: 0, minWidth: 120 },
    docLinha: {
      paddingVertical: 10,
      paddingHorizontal: 10,
      borderRadius: 8,
      backgroundColor: c.cardNested,
      borderWidth: 1,
      borderColor: c.border,
      marginBottom: 8,
    },
    /** Linha tocada / com detalhe aberto em baixo — destaque visível na lista. */
    docLinhaSelected: {
      backgroundColor: c.drawerItemActiveBg,
      borderWidth: 2,
      borderColor: c.accent,
    },
    docLinhaTit: { color: c.accentCode, fontWeight: '700', fontSize: 14 },
    docLinhaTitSelected: { color: c.text, fontWeight: '800' },
    docLinhaSub: { color: c.textSecondary, fontSize: 12, marginTop: 4 },
    docLinhaSubSelected: { color: c.textSecondary, fontSize: 12, marginTop: 4, fontWeight: '600' },
    docLinhaMeta: { color: c.success, fontSize: 12, marginTop: 6, fontWeight: '600' },
    scannerWrap: { flex: 1, backgroundColor: '#000', justifyContent: 'center' },
    scannerDenied: { flex: 1, justifyContent: 'center', padding: 24 },
    scannerDeniedTxt: { color: c.modalText, textAlign: 'center', fontSize: 16 },
    scannerClose: {
      position: 'absolute',
      top: 56,
      right: 16,
      backgroundColor: c.scannerCloseBg,
      paddingVertical: 10,
      paddingHorizontal: 16,
      borderRadius: 10,
    },
    scannerCloseTxt: { color: c.text, fontWeight: '700', fontSize: 16 },
  });
}
