import { StyleSheet } from 'react-native';
import { neonPrimaryButtonExtras } from './neonButtonExtras';
import type { ThemeColors } from './tokens';

export function buildConferenciaStyles(c: ThemeColors) {
  return StyleSheet.create({
    scroll: { flex: 1, backgroundColor: c.bg },
    container: { padding: 20, paddingBottom: 48 },
    center: { flex: 1, backgroundColor: c.bg, padding: 24, justifyContent: 'center' },
    title: { fontSize: 20, fontWeight: '800', color: c.text, marginBottom: 8 },
    hint: { fontSize: 14, color: c.textSecondary, lineHeight: 21, marginBottom: 16 },
    label: { color: c.formLabel, fontSize: 13, fontWeight: '600', marginBottom: 6 },
    input: {
      backgroundColor: c.inputBg,
      borderWidth: 1,
      borderColor: c.border,
      borderRadius: 10,
      padding: 14,
      color: c.text,
      fontSize: 16,
      marginBottom: 12,
    },
    inputQtd: {
      width: 96,
      backgroundColor: c.inputBg,
      borderWidth: 1,
      borderColor: c.border,
      borderRadius: 8,
      padding: 8,
      color: c.text,
      fontSize: 15,
      textAlign: 'right',
    },
    btn: {
      backgroundColor: c.primaryBtn,
      padding: 16,
      borderRadius: 10,
      alignItems: 'center',
      marginBottom: 10,
      ...neonPrimaryButtonExtras(c),
    },
    btnSecondary: {
      backgroundColor: c.secondaryBtn,
      padding: 14,
      borderRadius: 10,
      alignItems: 'center',
      marginBottom: 8,
    },
    btnSuccess: {
      backgroundColor: c.successBtn,
      padding: 16,
      borderRadius: 10,
      alignItems: 'center',
      marginTop: 8,
      ...neonPrimaryButtonExtras(c),
    },
    btnDisabled: { opacity: 0.5 },
    btnTextPrimary: { color: c.primaryBtnText, fontWeight: '700', fontSize: 16 },
    btnTextSecondary: { color: c.id === 'claroSistema' ? c.text : '#e2e8f0', fontWeight: '700', fontSize: 15 },
    meta: { fontSize: 12, color: c.textMuted, marginBottom: 12 },
    err: { color: c.err, marginBottom: 10, fontSize: 13 },
    warn: { color: c.warn, marginBottom: 10, fontSize: 13 },
    card: {
      marginTop: 16,
      padding: 16,
      backgroundColor: c.card,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: c.border,
    },
    cardTitle: { color: c.text, fontWeight: '700', fontSize: 16, marginBottom: 6 },
    cardLine: { color: c.textSecondary, fontSize: 13, marginBottom: 4 },
    subTitle: { color: c.formLabel, fontWeight: '700', marginTop: 14, marginBottom: 10, fontSize: 14 },
    itemRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: 10,
      paddingVertical: 10,
      borderBottomWidth: 1,
      borderBottomColor: c.rowBorder,
    },
    itemRowDivergencia: {
      borderLeftWidth: 4,
      borderLeftColor: c.err,
      paddingLeft: 10,
      marginLeft: -4,
      backgroundColor: c.cardNested ?? c.card,
      borderRadius: 8,
      marginBottom: 4,
      borderBottomWidth: 0,
    },
    itemMeta: { flex: 1 },
    codigo: { color: c.accentCode, fontWeight: '700', fontSize: 14 },
    codigoDivergencia: { color: c.err },
    desc: { color: c.textSecondary, fontSize: 12, marginTop: 2 },
    qtdNf: { color: c.textMuted, fontSize: 12, marginTop: 4 },
    itemHeaderRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: 8,
    },
    btnObsItem: {
      paddingHorizontal: 10,
      paddingVertical: 4,
      minWidth: 40,
      alignItems: 'center',
      justifyContent: 'center',
    },
    btnObsItemDots: { fontSize: 22, color: c.accent, fontWeight: '700', lineHeight: 24 },
    obsItemPreview: {
      color: c.textMuted,
      fontSize: 11,
      fontStyle: 'italic',
      marginTop: 6,
    },
    modalBackdrop: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.55)',
      justifyContent: 'center',
      padding: 24,
    },
    modalCard: {
      backgroundColor: c.card,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: c.border,
      padding: 18,
    },
    modalTitle: { color: c.text, fontWeight: '800', fontSize: 17, marginBottom: 6 },
    modalSubtitle: { color: c.textSecondary, fontSize: 13, marginBottom: 12 },
    modalInputObs: {
      backgroundColor: c.inputBg,
      borderWidth: 1,
      borderColor: c.border,
      borderRadius: 10,
      padding: 12,
      color: c.text,
      fontSize: 15,
      minHeight: 100,
      textAlignVertical: 'top',
    },
    modalActions: { flexDirection: 'row', justifyContent: 'flex-end', gap: 12, marginTop: 16 },
    modalBtnGhost: { paddingVertical: 12, paddingHorizontal: 16 },
    modalBtnGhostText: { color: c.accent, fontWeight: '700', fontSize: 15 },
    modalBtnPrimary: {
      backgroundColor: c.primaryBtn,
      paddingVertical: 12,
      paddingHorizontal: 18,
      borderRadius: 10,
      ...neonPrimaryButtonExtras(c),
    },
    modalBtnPrimaryText: { color: c.primaryBtnText, fontWeight: '800', fontSize: 15 },
    docLinha: {
      paddingVertical: 10,
      paddingHorizontal: 10,
      borderRadius: 8,
      backgroundColor: c.cardNested ?? c.card,
      borderWidth: 1,
      borderColor: c.border,
      marginBottom: 8,
    },
    docLinhaSelected: {
      backgroundColor: c.drawerItemActiveBg,
      borderWidth: 2,
      borderColor: c.accent,
    },
    docLinhaTit: { color: c.accentCode, fontWeight: '700', fontSize: 14 },
    docLinhaTitSelected: { color: c.text, fontWeight: '800' },
    docLinhaSub: { color: c.textSecondary, fontSize: 12, marginTop: 4 },
    docLinhaSubSelected: { color: c.textSecondary, fontSize: 12, marginTop: 4, fontWeight: '600' },
    docLinhaMeta: { color: c.textMuted, fontSize: 11, marginTop: 4 },
    docLinhaMetaSelected: { color: c.accent, fontWeight: '700', fontSize: 11, marginTop: 4 },
  });
}
