import { StyleSheet } from 'react-native';
import { neonPrimaryButtonExtras } from './neonButtonExtras';
import type { ThemeColors } from './tokens';

export function buildInventarioStyles(c: ThemeColors) {
  return StyleSheet.create({
    center: { flex: 1, padding: 24, justifyContent: 'center', backgroundColor: c.bg },
    scroll: { flex: 1, backgroundColor: c.bg },
    container: { padding: 20, paddingBottom: 40 },
    title: { fontSize: 22, fontWeight: '800', color: c.text, marginBottom: 10 },
    hint: { fontSize: 14, color: c.textSecondary, lineHeight: 22, marginBottom: 16 },
    hintSmall: { fontSize: 13, color: c.textMuted, lineHeight: 19, marginBottom: 10 },
    meta: { fontSize: 12, color: c.textMuted, marginBottom: 8 },
    err: { color: c.err, marginBottom: 8, fontSize: 13 },
    btn: {
      backgroundColor: c.primaryBtn,
      padding: 16,
      borderRadius: 10,
      alignItems: 'center',
      marginBottom: 10,
      ...neonPrimaryButtonExtras(c),
    },
    btnText: { color: c.primaryBtnText, fontWeight: '700', fontSize: 16 },
    card: {
      marginTop: 12,
      padding: 16,
      backgroundColor: c.card,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: c.border,
    },
    cardTitle: { color: c.text, fontWeight: '800', fontSize: 16 },
    cardSub: { color: c.textSecondary, fontSize: 13, marginTop: 4 },
    rowMeta: { color: c.textMuted, fontSize: 12, marginTop: 8 },
    badge: {
      alignSelf: 'flex-start',
      marginTop: 8,
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 999,
      backgroundColor: c.cardNested,
      borderWidth: 1,
      borderColor: c.border,
    },
    badgeText: { fontSize: 12, fontWeight: '700', color: c.accent },
    detailHint: { fontSize: 13, color: c.textSecondary, lineHeight: 20, marginBottom: 12 },
    itemCard: {
      marginTop: 10,
      padding: 14,
      backgroundColor: c.card,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: c.border,
    },
    itemCodigo: { color: c.text, fontWeight: '800', fontSize: 15 },
    itemDesc: { color: c.textSecondary, fontSize: 13, marginTop: 4 },
    itemRow: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', marginTop: 10, gap: 8 },
    itemLabel: { color: c.textMuted, fontSize: 12, width: 120 },
    qtdInput: {
      minWidth: 100,
      flex: 1,
      maxWidth: 160,
      borderWidth: 1,
      borderColor: c.border,
      borderRadius: 8,
      paddingHorizontal: 10,
      paddingVertical: 8,
      color: c.text,
      backgroundColor: c.cardNested,
      fontSize: 16,
      fontWeight: '600',
    },
    locInput: {
      flex: 1,
      minWidth: 120,
      borderWidth: 1,
      borderColor: c.border,
      borderRadius: 8,
      paddingHorizontal: 10,
      paddingVertical: 8,
      color: c.text,
      backgroundColor: c.cardNested,
      fontSize: 15,
    },
    searchRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      marginBottom: 10,
    },
    searchInput: {
      flex: 1,
      borderWidth: 1,
      borderColor: c.border,
      borderRadius: 10,
      paddingHorizontal: 12,
      paddingVertical: 10,
      color: c.text,
      backgroundColor: c.inputBg,
      fontSize: 15,
    },
    scanBtn: {
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderRadius: 10,
      backgroundColor: c.cardNested,
      borderWidth: 1,
      borderColor: c.border,
    },
    scanBtnText: { color: c.accent, fontWeight: '800', fontSize: 14 },
    focoCard: {
      marginBottom: 12,
      padding: 14,
      borderRadius: 12,
      borderWidth: 2,
      borderColor: c.accent,
      backgroundColor: c.sessaoBg,
    },
    focoTit: { color: c.accent, fontWeight: '800', fontSize: 13, marginBottom: 8 },
    divergeBadge: {
      marginTop: 8,
      color: c.warn,
      fontSize: 12,
      fontWeight: '700',
    },
    scannerWrap: { flex: 1, backgroundColor: '#000', justifyContent: 'center' },
    scannerClose: {
      position: 'absolute',
      bottom: 40,
      alignSelf: 'center',
      paddingHorizontal: 24,
      paddingVertical: 12,
      backgroundColor: 'rgba(0,0,0,0.7)',
      borderRadius: 10,
    },
    scannerCloseTxt: { color: '#fff', fontWeight: '700', fontSize: 16 },
    btnSecondary: {
      backgroundColor: c.cardNested,
      padding: 14,
      borderRadius: 10,
      alignItems: 'center',
      marginBottom: 10,
      borderWidth: 1,
      borderColor: c.border,
    },
    btnSecondaryText: { color: c.text, fontWeight: '700', fontSize: 15 },
  });
}
